server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  signerKey: "78f8f2012ec35af521e11105a909b6323855a4f7c80edf5d459b0b92e88c98e6"